### PR TITLE
Fix concurrent modification error in GrpcWebClientChannel.terminate

### LINKED ISSUE #331: Error when terminating web connections.
When calling `terminate()` on a GRPC web channel the following exception is thrown:

`error closing channel: Concurrent modification during iteration: Instance of '_HashSet<XhrTransportStream>'.`

## Repro steps

1. Create multiple web streams.
1. Call `terminate()` on the GRPC web channel.

Expected result: I expect existing calls and streams to be terminated.

Actual result: An exception is thrown and it looks like existing calls are kept open. The following exception is also displayed.

## Details

```
Error: Bad state: Cannot add event after closing
    at Object.throw_ [as throw] (http://localhost:49717/dart_sdk.js:4330:11)
    at _AsyncStreamController.new.addError (http://localhost:49717/dart_sdk.js:33436:55)
    at ClientCall.new.[_onRequestError] (http://localhost:49717/packages/grpc/src/client/connection.dart.lib.js:538:26)
    at http://localhost:49717/packages/grpc/src/client/transport/xhr_transport.dart.lib.js:138:27
    at Object._checkAndCall (http://localhost:49717/dart_sdk.js:4540:16)
    at Object.dcall (http://localhost:49717/dart_sdk.js:4545:17)
    at XMLHttpRequest.<anonymous> (http://localhost:49717/dart_sdk.js:104837:21)
    at xhr_transport.XhrTransportStream.new.terminate (http://localhost:49717/packages/grpc/src/client/transport/xhr_transport.dart.lib.js:108:25)
    at terminate.next (<anonymous>)
    at runBody (http://localhost:49717/dart_sdk.js:37387:34)
    at Object._async [as async] (http://localhost:49717/dart_sdk.js:37418:7)
    at xhr_transport.XhrTransportStream.new.terminate (http://localhost:49717/packages/grpc/src/client/transport/xhr_transport.dart.lib.js:106:20)
    at ClientCall.new._terminate (http://localhost:49717/packages/grpc/src/client/connection.dart.lib.js:571:36)
    at _terminate.next (<anonymous>)
    at runBody (http://localhost:49717/dart_sdk.js:37387:34)
    at Object._async [as async] (http://localhost:49717/dart_sdk.js:37418:7)
    at ClientCall.new.[_terminate] (http://localhost:49717/packages/grpc/src/client/connection.dart.lib.js:564:22)
    at ClientCall.new._safeTerminate (http://localhost:49717/packages/grpc/src/client/connection.dart.lib.js:585:35)
    at _safeTerminate.next (<anonymous>)
    at runBody (http://localhost:49717/dart_sdk.js:37387:34)
    at Object._async [as async] (http://localhost:49717/dart_sdk.js:37418:7)
    at ClientCall.new.[_safeTerminate] (http://localhost:49717/packages/grpc/src/client/connection.dart.lib.js:583:22)
    at ClientCall.new.[_onTimedOut] (http://localhost:49717/packages/grpc/src/client/connection.dart.lib.js:442:29)
    at internalCallback (http://localhost:49717/dart_sdk.js:23542:11)
```

### PR DESCRIPTION
**Pull request by isaldana**
Fixes #331

### CODE REVIEW

**Comment by mit-mit** [comment]
cc @mraleph

**Comment by mit-mit** [comment]
@isaldana you mentioned in https://github.com/grpc/grpc-dart/issues/306#issuecomment-663742212 that this might also fix https://github.com/grpc/grpc-dart/issues/206 ?

**Comment by isaldana** [comment]
@mit-mit I think so. The `cancel()` call eventually calls `terminate()` on the stream as show here https://github.com/grpc/grpc-dart/blob/master/lib/src/client/call.dart#L328. So this addresses the issue with `terminate()` on web.

File: lib/src/client/transport/xhr_transport.dart [hunk 1]
```diff
@@ -180,8 +180,9 @@ class XhrClientConnection extends ClientConnection {
 
   @override
   Future<void> terminate() async {
-    for (XhrTransportStream request in _requests) {
-      request.terminate();
+    while (_requests.isNotEmpty) {
+      final XhrTransportStream request = _requests.first;
```
Comment (mraleph) [inline lib/src/client/transport/xhr_transport.dart:184]: I would suggest:

```dart
while (_requests.isNotEmpty) {
  final requests = List.of(_requests);
  _requests.clear();

    
  await Future.wait(requests.map((rq) => rq.terminate()));
}
```

this would `terminate()` all requests in parallel rather then sequentially.

**Review by mraleph — CHANGES_REQUESTED** [review]
Thanks for the contribution and sorry for the delay with reviews.

File: lib/src/client/transport/xhr_transport.dart (hunk 1 above)
Comment (isaldana) [reply lib/src/client/transport/xhr_transport.dart]: @mraleph AFAIK, there is no need to wait for the requests to terminate. It was just the nature of the loop since I didn't want to copy the requests list. I made the change to copy the list of requests and call terminate on them.

Comment (isaldana) [reply lib/src/client/transport/xhr_transport.dart]: @mraleph Please hold on before merging this. I've been running https://github.com/isaldana/grpc-dart for a while and I just realized that I forgot to include https://github.com/isaldana/grpc-dart/commit/0d23114b449f4a5e65d170c6471ab9a9ccc05d3d in this PR.

**Comment by mraleph** [comment]
@isaldana is this in a mergable? Could you rebase and add a test. We now have a gRPC-web testing harness you could use.

**Review by mraleph — APPROVED** [review]
I have added test and going to merge.
