### PR TITLE
Switch to Dart 3

### LINKED ISSUE #613: Dart 3 compatibility: `_ResponseMixin` should be changed to be an actual `mixin`
This definition should be changed to `mixin`:
https://github.com/grpc/grpc-dart/blob/eb833d3f1c4ee9b588fe6bf5e18ed476edb938f9/lib/src/client/common.dart#L80

Otherwise this will fail to build if Dart language version 3 is used.
https://github.com/grpc/grpc-dart/blob/eb833d3f1c4ee9b588fe6bf5e18ed476edb938f9/lib/src/client/common.dart#L46

The change will be fully backwards-compatible (it's a private symbol), so it can be applied sooner rather than later.

### PR DESCRIPTION
**Pull request by mosuem**
Fixes #613 .

### CODE REVIEW

File: test/timeline_test.dart [hunk 1]
```diff
@@ -64,78 +67,13 @@ class FixedConnectionClientChannel extends ClientChannelBase {
...
-Future<void> testee() async {
+Future<VmService> testee() async {
+  isTimelineLoggingEnabled = true;
+  final info = await dev.Service.getInfo();
+  final uri = info.serverWebSocketUri!;
+  final vmService = await vmServiceConnectUri(uri.toString());
   final server = Server.create(services: [TestService()]);
   await server.serve(address: 'localhost', port: 0);
-  isTimelineLoggingEnabled = true;
-  timelineTaskFactory = fakeTimelineTaskFactory;
```
Comment (mraleph) [inline test/timeline_test.dart:138]: You should probably remove this field and all its uses as well.

**Review by mraleph — APPROVED** [review]
