### PR TITLE
Custom Error Handling for Server

### LINKED ISSUE #51: Add logger for debugging
It would be really great if this package would use a (logging-compliant) logger that could be set to get better reporting when things go wrong.

### PR DESCRIPTION
**Pull request by bgetsug**
This picks up where #520 left off and resolves #51.

My particular use case is needing to log (with stack traces) gRPC errors as they occur on the server, such as those having to do with deserialization.

cc: @mraleph

### CODE REVIEW

File: lib/src/server/handler.dart [hunk 1]
```diff
@@ -61,9 +62,14 @@ class ServerHandlerImpl extends ServiceCall {
   Timer? _timeoutTimer;
   final X509Certificate? _clientCertificate;
 
-  ServerHandlerImpl(this._serviceLookup, this._stream, this._interceptors,
-      this._codecRegistry,
-      [this._clientCertificate]);
+  ServerHandlerImpl(
```
Comment (mraleph) [inline lib/src/server/handler.dart:65]: Could you convert this one to use named parameter as well, so that call-sites are more readable?

Comment (bgetsug) [reply lib/src/server/handler.dart]: Done 😄

File: lib/src/server/server.dart [hunk 2]
```diff
@@ -87,6 +87,7 @@ class ConnectionServer {
   final Map<String, Service> _services = {};
   final List<Interceptor> _interceptors;
   final CodecRegistry? _codecRegistry;
+  final Function? _errorHandler;
```
Comment (mraleph) [inline lib/src/server/server.dart:90]: This should be tighter typed (here and other places which accept it), e.g. 

```
typedef ErrorHandler = void Function(GrpcError error, StackTrace? trace);
```
otherwise users don't actually know what kind of function they are expected to pass in.

File: lib/src/server/handler.dart [hunk 3]
```diff
@@ -410,7 +423,11 @@ class ServerHandlerImpl extends ServiceCall {
       ..onDone(_onDone);
   }
 
-  void _sendError(GrpcError error) {
+  void _sendError(GrpcError error, [StackTrace? trace]) {
+    if (_errorHandler != null) {
+      _errorHandler!(error, trace);
```
Comment (mraleph) [inline lib/src/server/handler.dart:428]: This could simply be: `_errorHandler?.call(error, trace)` - then `if` is not needed.

**Review by mraleph — CHANGES_REQUESTED** [review]
Two final comments - and then I will merge. Thanks a bunch for pushing this through.

File: lib/src/server/handler.dart (hunk 3 above)
Comment (bgetsug) [reply lib/src/server/handler.dart]: nice...I never think to use `call()`

File: lib/src/server/server.dart (hunk 2 above)
Comment (bgetsug) [reply lib/src/server/server.dart]: ✅

**Comment by long1eu** [comment]
Can we have this on pub.dev?

**Comment by Pingear** [comment]
Hello !
where can I find documentation on the new logging functionality?
